### ISSUE TITLE
enabling in evil-mode

### ISSUE THREAD

**Issue by ohspite** [k-talo/volatile-highlights.el#13]
The instructions in the README for enabling in evil-mode have the line
```
  (vhl/define-extension 'evil 'evil-yank 'evil-move)
```

Nothing was happening for me when I inserted copied/killed text in evil-mode.  I think the problem is that `yank` in vim means to copy rather than to insert.  I changed that line to
```
  (vhl/define-extension 'evil 'evil-paste-after 'evil-paste-before 'evil-paste-pop 'evil-move)
```
 and things seem to be working fine now.

**Comment by k-talo** [comment]
Since I'm not a vim guy, I've been misunderstood the meaning of `yank'. Thanks for your reporting.
