### ISSUE TITLE
No primary method error.  

### ISSUE THREAD

**Issue by adriandeveloper** [k-talo/volatile-highlights.el#15]
I'm using Emacs 25.1.1 with Spacemacs. 

I keep getting this error when loading up the software. 

"Error (use-package): volatile-highlights :config: No primary method: cl-generic-generalizers, (eql etags)"

![screen shot 2016-09-30 at 6 29 11 pm](https://cloud.githubusercontent.com/assets/3031275/19011930/1432d1bc-876b-11e6-84c5-ba6d2fc78522.png)

Could you help with this?

**Comment by k-talo** [comment]
Can you show me the backtrace of the error?
