### ISSUE TITLE
Make highlight color configurable

### ISSUE THREAD

**Issue by tastytea** [k-talo/volatile-highlights.el#21]
Sometimes the highlight makes the text unreadable.

![screenshot_2020-04-28T19-42-56](https://user-images.githubusercontent.com/3681516/80519672-a0874a80-8988-11ea-8974-3d252c01ebe8.png)

**Comment by k-talo** [comment]
Would you try customizing the face by: 

M-x customize-face <RET> vhl/default-face <RET>

**Comment by tastytea** [comment]
Thanks, I didn't catch that with the acronym. 🙂
