### ISSUE TITLE
'pushnew' is an obsolete alias (as of 27.1)

### ISSUE THREAD

**Issue by diamond-lizard** [k-talo/volatile-highlights.el#23]
When loading volatile-highlights.el, Emacs complains:

    volatile-highlights.el: Warning: 'pushnew' is an obsolete alias (as of 27.1); use 'cl-pushnew' instead.

**Comment by pataquets** [comment]
@diamond-lizard Fancy to try the fix at #22 and report back (in hopes it speeds up merging)?
