### ISSUE TITLE
Enable Volatile highlights for Evil operations? 

### ISSUE THREAD

**Issue by ReneFroger** [k-talo/volatile-highlights.el#7]
With the [guide on extending Emacs](http://tuhdo.github.io/emacs-tutor3.html), I discovered your package [volatile highlights package](http://www.emacswiki.org/emacs/VolatileHighlights). And I really appreciate it, thanks for sharing it!

But it works only on Emacs operations like kill and yank. I would apply it too on Evil operations like evil-yank, move, and paste. Would it be possible to add support for Evil operations?

**Comment by uu1101** [comment]
I've been using the following since a long time:

~~~{.elisp}
(vhl/give-advice-to-make-vhl-on-changes evil-paste-after)
(vhl/give-advice-to-make-vhl-on-changes evil-paste-before)
(vhl/give-advice-to-make-vhl-on-changes evil-paste-pop)
~~~

@k-talo, thank you for this package :-).

**Comment by ReneFroger** [comment]
I solved it on the other place: 

http://emacs.stackexchange.com/questions/12909/how-can-i-get-volatilehighlights-to-work-with-evil-yank-evil-delete-etc/13054#13054

But thanks for your help, uu1101, it's really appreciated. THanks!

**Comment by uu1101** [comment]
You are welcome
